name: build-pyauditor-macos

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build-pyauditor:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
        
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: cache-dependencies-pyauditor
          
      # We need to somehow get the SQLX_OFFLINE env variable into the container.
      # Since `maturin-action` doesn't enable us to do that, we have to tell cargo
      # via its configuration.
      - name: Create fake .cargo/config.toml
        run: |
          mkdir -p .cargo
          echo -e "[env]\nSQLX_OFFLINE = \"true\"" >> .cargo/config.toml

      - name: Maturin
        uses: messense/maturin-action@v1
        with:
          maturin-version: v1.2.3
          command: build
          args: --release -o dist --target universal2-apple-darwin --interpreter python${{ inputs.python-version }} --manifest-path pyauditor/Cargo.toml

      - name: Upload wheel
        uses: actions/upload-artifact@v6
        with:
          path: dist
          name: pyauditor-wheels-macos-${{ inputs.python-version }}
