name: python-code-tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        
jobs:
  unit-tests-apel-plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/apel
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
      - name: Download wheel
        uses: actions/download-artifact@v7
        with:
          path: ./plugins/apel
          name: pyauditor-wheels-linux-${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install *.whl
          pip install -e .[tests]
      - name: Run pytest
        run: pytest
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./plugins/apel/lcov.info
          fail_ci_if_error: true
          token: ef0e698e-e1de-4603-88fa-b3d7c10fb0e1
          #${{ secrets.CODECOV_TOKEN }} doesn't work for PRs from forks
  mypy-apel-plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/apel
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
      - name: Download wheel
        uses: actions/download-artifact@v7
        with:
          path: ./plugins/apel
          name: pyauditor-wheels-linux-${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install *.whl
          pip install -e .[tests]
      - name: Run mypy
        run: mypy .
